---
- hosts: all
  become: yes
  vars:
    server_name: "{{ ansible_default_ipv4.address }}"
    document_root: /var/www
    app_root: html_demo_site-main
  tasks:
    
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'
    - name: Update apt cache and install utw
      apt:
        name: ufw
        state: latest
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Update apt cache and install Nginx
      yum:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'
    - name: Update apt cache and install utw
      yum:
        name: ufw
        state: latest
        update_cache: yes
      when: ansible_os_family == 'RedHat'

    - name: Copy website files to the server's document root
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve

    - name: Creates directory for CentOS
      file:
        path: /etc/nginx/sites-available
        state: directory
      when: ansible_os_family == 'RedHat'

    - name: Creates directory for CentOS
      file:
        path: /etc/nginx/sites-enabled
        state: directory
      when: ansible_os_family == 'RedHat'

    - name: Apply Nginx template
      template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx

    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: stop